---
     - name: Creating a security group
       ec2_group:
            name: "{{ security_group }}"
            description: sg with rule descriptions
            region: "{{ region  }}"
            rules:
               - proto: tcp
                 from_port: 22
                 to_port: 22
                 cidr_ip: 0.0.0.0/0     
               - proto: tcp
                 from_port: 80
                 to_port: 80
                 cidr_ip: 0.0.0.0/0
     
     - name: launch the ec2 instance
       ec2:
            key_name: "{{ keypair  }}"
            instance_type: "{{ instance_type  }}"
            image: "{{ image  }}"
            region: "{{ region  }}"
            wait: yes
            group: "{{ security_group  }}"
            count: "{{ count  }}"
       register: ec2

     - debug:
         var: ec2.instances

     - local_action: copy content={{ ec2.instances }} dest=/root/ec2/files/fact.txt
